def run_game():
    print ("Try again?")
    answer = input("yes or no ")
    if answer == "yes":
        exec(open("mygame.py").read())
    if answer == "":
        quit("mygame.py")
        
print ("You are about to embark on a perilous journey")
print ("unlike anything you've ever seen before.")
print ("Before we begin, think long and hard about whether")
print ("or not you'd like to turn back.")
print ("Now then, are you ready to begin?")
response = input('Choose your destiny: yes or no ')
if response == "no":
    print ("Understandable, have a nice day.")
    print ("Ending 1 of 30: THE QUITTER")
    run_game()
if response == "maybe":
    print ("Indecisiveness is not recommended for life changing adventures.")
    print ("Please try again.")
    print ("Ending 2 of 30: THE INDECISIVE")
    run_game()
if response == "yes":     
    print ("Very well. Let us begin")
    print ("You awaken from your slumber in a cold sweat.")
    print ("Disoriented. you stumble across your bedroom to the light switch and turn the lights on.")
    print ("In a daze, you check your phone to look at the time: 3 a.m.")
    print ("You could go back to sleep, but alternatively, you could move to another room")
    print ("What will you do?")
    decision = input('go to sleep or type kitchen, bathroom, garage or gaming room: ')
    if decision == "go to sleep":
        print ("You remember you have things to do in the morning before work.")
        print ("You throw yourself on to your bed to get some shut-eye.")
        print ("Still, you wonder what could have been had you gone out.")
        print ("All throughout the night, you envision a room underneath your house")
        print ("Filled with unbelievable wealth, prosperity and adventure")
        print ("Ending 3 of 30: THE TIRED")
        run_game()
    if decision == "kitchen":            
        print ("You decide to go into the kitchen. You are very hungry after all.")
        print ("There's a number of things you could potentially make, but you shouldn't be too loud.")
        print ("What will you make, weary traveler?")
        food = input ('grilled cheese, waffles, or souffle: ')
        if food == "souffle":
            print ("Um, it's three in the morning. Are you sure tha-")
            print ("Whatever, you're the one that chose it")
            print ("After painstakingly measuring all ingredients you throw them in the oven")
            print ("However, the process has made you weary and exhausted.")
            print ("You doze off. When you wake up, you find yourself in a hospital bed.")
            print ("You realize you overslept and your souffle caught fire.")
            print ("You are currently being treated for smoke inhalation.")
            print ("Let this be a lesson kids. NEVER make a souffle at 3 a.m.")
            print ("Ending 4 of 30: THE FOOL")
            run_game() 
        elif food == "grilled cheese":
            print ("A simple and easy matter, you throw the sandwich onto the pan.")
            print ("The butter sizzles as you expertly manage to cook both sides perfectly.")
            print ("After cutting up an apple, you have the best 3 a.m. meal of your lifetime.")
            print ("You decide to go back to bed with a full belly, ready for tomorrow may bring")
            print ("Ending 5 of 30: THE HAPPY")
            run_game() 
        elif food == "waffles":
            print ("Great idea! It's early in the morning, a perfect time for early breakfast.")
            print ("You prepare the batter and slowly pour it into the waffle iron.")
            print ("Before you know it, you are the proud consumer of 6 waffles.")
            print ("Looking to your right, you are startled to see a donkey in your house!")
            print ("The donkey seems to be eying your waffles.")
            print ("Will you give the donkey one of your waffles?")
            donkey = input('yes or no: ')
            if donkey == "no":
                print ("You refuse to share any of your waffles with the donkey.")
                print ("The donkey is mad at you, and proceeds to kick you in the groin.")
                print ("You now know the pain the donkey feels.")
                print ("Ending 6 of 30: THE SELFISH")
                run_game()
            elif donkey == "yes":
                print ("You decide to be kind and courteous and share your delicious waffles with the donkey.")
                print ("The donkey is very happy and transports you to the swamp where all of its friends live.")
                print ("You and the donkey have now become lifelong buddies!")
                print ("Ending 7 of 30: THE ALL STAR")
                run_game()
    if decision == "bathroom":
        print ("You have some unfinished buisness with your bathroom.")
        print ("You drag yourself across the hall and make it to the legendary tiled flooring.")
        print ("As you see your reflection, it's time to contemplate what your mission is...")
        poop = input('take a shower, do your buisness or wash your face: ')
        if poop == "take a shower":
            print ("You decide to take a shower. All that sweating made you quite the stinker.")
            print ("In the middle of your delightful shower, you notice a strange silhoutte through your shower curtains.")
            print ("Will you investigate further?")
            psycho = input('yes or no: ')
            if psycho == "yes":
                print ("You pull back the curtains and find nothing. It was just your imagination")
                print ("You finish your shower and head back to sleep. Unfortunately, you forgot to dry your head.")
                print ("You wake up with bedhead. You've met with a terrible fate.")
                print ("Ending 8 of 30: THE UNFORTUNATE")
                run_game()
            elif psycho == "no":
                print ("It's probably nothing. After all, you live by yourself. Who would even be up at 3 in the morning?")
                print ("As you continue bathing, the curtains suddenly pull open! You see a crazy person with a knife!")
                print ("You are stabbed multiple times and your consciousness slowly fades.")
                print ("Your last memory on this planet is that of chocolate syrup running down your drain.")
                print ("Ending 9 of 30: THE DECEASED.")
                run_game()
        elif poop == "do your buisness":
            print ("You feel you stomach grumble as one thing is apparent. It's THAT time again.")
            print ("You open up the porcelain throne as you prepare to drop a bomb.")
            print ("You hear an odd growl as you continue to do your buisness.")
            print ("You shriek in terror to find that a snake has somehow crawled its way up your pipes!")           
            print ("What will you do?")
            snake = input('flush the toilet or run away: ')
            if snake == 'flush the toilet':
                print ("In a panic, you clench with all your might and flush the toilet!")
                print ("The snake and your buisness are sent back to the depths from whence they came.")
                print ("Exhausted, you clean up after yourself and head back to bed")
                print ("Ending 10 of 30: THE CLUTCH")
                run_game()
            elif snake == "run away":
                print ("You run out of your house screaming with your pants around your ankles.")
                print ("Your wails of fear have woken up the entire neighborhood, who see you in this state of blind panic")
                print ("Even the snake has come outside to see you in this hillarious state.")
                print ("Ending 11 of 30: THE EMBARRASSED")
                run_game()
        if poop == "wash your face":
            print ("You wash you face as you contemplate some recent events in your life.")
            print ("You recently recieved a chalice from your deceased uncle's estate.")
            print ("He is said to have unearthed some sort of secret from it, but it's unknown how.")
            print ("You stored it in a room below your house along with some other artifacts of times long past.")
            print ("You shrug it off for now, and head back to your room to get some sleep.")
            print ("Ending 12 of 30: THE PROPHECY")
            run_game()
    if decision == "garage":
        print ("You decide to go on a roadtrippin adventure in your trusty vehicle.")
        print ("Wait, what is your trusty vehicle again?")
        steed = input('Choose your ride, motorcycle or car: ')
        if steed == "motorcycle":
            print ("Awwwww yeah, you take your motorcycle out on the road for a spin!")
            print ("Before you know it, you're cruisin' down the highway like the badass you are.")
            print ("Unfortunately, the police officer behind you does not agree, as they turn their lights on.")
            print ("How will the badass respond?")
            popo = input('choose violence or be responsible: ')
            if popo == "choose violence":
                print ("You woke up today and chose violence. Nothing's gonna stop your vibe!")
                print ("You speed forward and see the cop behind you... slow down?")
                print ("You look forward and see a sign that says STOP CONSTRUCTION AHEAD")
                print ("You then plow headfirst into a tractor. Vision fading, the last thing you hear is someone calling you a dumbass")
                print ("Ending 13 of 30: THE RECKLESS")
                run_game()
            elif popo == "be responsible":
                print ("You let the officer catch up to you. You are led away in handcuffs.")
                print ("Wait... the officer isn't taking you to the police station. What's going on here?")
                print ("Hey, this is your friends house!")
                print ("SURPRISE!!!")
                print ("It's your birthday! All your friends put together a 3am birthday party just for you!")
                print ("How lucky you are to have such great friends :)")
                print ("Ending 14 of 30: THE FORTUNATE")
                run_game()
        elif steed == "car":
            print ("BEEP BEEP, BEEP BEEP, YEAH!")
            print ("You decide to drive your car to McDonalds to grab something to eat.")
            print ("But what WILL you eat???")
            mcd = input('ice cream, soda or a Big Mac: ')
            if mcd == "ice cream":
                print ("Did you really expect the ice cream machine NOT to be broken at 3 am?")
                print ("Ending 15 of 30: BROKEN DREAMS")
                run_game()
            elif mcd == "soda":
                print ("You ask for a soda and roll up to the window")
                print ("As you grab your drink, it falls out of your hand and the drink spills directly on to your crotch")
                print ("You are wide awake now.")
                print ("Ending 16 of 30: THE AWAKENED")
                run_game()
            elif mcd == "big mac":
                print ("You grab a Big Mac, go home and crawl bac into bed.")
                print ("You devour the Big Mac in only a few bites. You had no idea you were this hungry until just now.")
                print ("You go back to sleep, satiated and satisfied. At least until tomorrow morning.")
                print ("Ending 17 of 30: THE BIG MAC HERO")
                run_game()
    if decision == "gaming room":
        print ("You decide that the early morning is peak gamer time!")
        print ("As you sit in your gaming chair, you ponder what to play...")
        game = input('rpg, action or casual')
        if game == "rpg":
            print ("Time to play some Pokemon!")
            print ("A trainer walks up to you and wishes to battle! They send out their Venusaur!")
            print ("Which Pokemon will you send out?")
            pokemon = input('blastoise or charizard: ')
            if pokemon == "blastoise":
                print ("You send out blastoise, who puts up a valiant effort, yet unfortunately falls in battle")
                print ("As your character blacks out, so do you, spiraling into darkness.")
                print ("Ending 18 of 30: THE VERY WORST")
                run_game()
            elif pokemon == "charizard":
                print ("Your charizard makes quick work of venusaur, and the opposing trainer is forced to give you money.")
                print ("Oddly enough, you get a notification on your phone: $100 was deposited to your bank account.")
                print ("You could question what just happened, but rather than do that, you just smile and go back to sleep.")
                print ("Ending 19 of 30: THE VERY BEST")
                run_game()
        elif game == "action":
                print ("Aw yeah, time to hop on and play some Call of Duty!")
                print ("As always you immaculately pull off a 360 no scope on your opponet.")
                print ("They however are not very happy with your achievement and angrily throw insults at you")
                print ("You clapback with even better insults, but immediately go silent when you hear knocking at your door.")
                print ("You open the door as someone jumps in the air, spins in a circle and fires a gun at you.")
                print ("Ending 20 of 30: THE REKT")
                run_game()
        elif game == "casual":
            print ("Animal Crossing time!")
            print ("It's 3am so sadly none of your villagers are awake. But you can still be productive!")
            animal == input('go fishing or catch bugs: ')
            if animal == "go fishing":
                print ("You decide to go fishing by the beach!")
                print ("You caught: A sea bass")
                print ("You decide to try again. Another one.")
                print ("After 10 additional sea bass, you finally catch a red snapper!")
                print ("It bites your hand and swims back into the ocean.")
                print ("Ending 21 of 30: THE SEA BASS KING")
                run_game()
            elif animal == "catch bugs":    
                print ("You want to catch a bagworm so you start shaking trees until you encouter-")
                print ("BEES?!?!")
                print ("You quickly dash away from the bees, but in doing so you trip and fall into a nearby river")
                print ("You are swept off into the ocean, never to be heard from again")
                print ("Ending 22 of 30: THE DROWNED")
                run_game()
    if decision == "basement":
        print ("Oh yeah, you do have a basement! You decide to check it out.")
        print ("You see a box with a few of your family's relics.")
        print ("You decide to look at them closer.")
        box = input('cufflinks, sword, or painting: ')
        if box == "chalice":
            print ("You move the contents of the box around to discover a chalice.")
            print ("Recently, this artifact from the Middle East was given to you from your deceased uncles estate.")
            print ("You pick up the chalice. It's shiny interior beckons you to drink out of it.")
            print ("What will you drink out of it?")
            drink = input ('wine or water: ')
            if drink == "wine":
                print ("You chose: poorly")
                print ("After taking a swig of wine from the chalice, your bones begin to age like fine wine.")
                print ("Slowly, every fabric of your being is evicerated into dust")
                print ("Ending 23 of 30: DUST IN THE WIND")
                run_game()
            elif drink == "water":
                print ("You chose: wisely")
                print ("You drink the water and before you know it are eye to eye with your deceased uncle!")
                print ("Congratulations, my nephew. You are truly spectacular. You have won this game called life.")
                print ("Now go, and rest well for your next great adventure.")
                print ("Ending 30 of 30: THE WINNER")
        elif box == "cufflinks":
            print ("You pick up your grandpa's cufflinks. You have no idea why they were passed down to you, but oh well.")
            print ("You decide to take them to a pawn shop. A middle aged bald man is behind the counter.")
            print ("He offers you $100 bucks for them.")
            offer = input('haggle, barter, or accept offer: ')
            if offer == "haggle":
                print ("The bald man accosts you, stating he has to make money somehow")
                print ("After tight negotiations it's clear you won't make a deal.")
                print ("He points at the door and waves you out of the shop")
                print ("Ending 24 of 30: THE PENNY PINCHER")
            elif offer == "accept offer":
                print ("You accept his offer and walk out of the store with 100 bucks.")
                print ("Ending 25 of 30: THE HIGH ROLLER")
                run_game()
            elif offer == "barter":
                print ("You notice a boomerang on display in the back of the shop in exchange for the cufflinks")
                print ("The man aggrees and you walk out of the shop with a rad boomerang!")
                print ("You throw the boomerang. It comes flying back at you and hits you in the head.")
                print ("Ending 26 of 30: WASTED")
                run_game()
        elif box == "sword":
            print ("Before you can even pick up the sword, you stumble into the box and blade pierces through you.")
            print ("You slowly lose consciousness as you notice something glimmering in the box")
            print ("Ending 27 of 30: THE SLAIN")
            run_game()
        elif box == "painting":
            print ("You look into thw painting of a grasst plain and are instantly sucked into the landscape.")
            print ("You are confronted by a horned turtlw who looks like he's about to breathe fire on you!")
            print ("What will you do?")
            action = input ('jump or grab tail: ')
            if action == "jump":
                print ("You launch yourself into the air, but before you even have a chance to land the turtle roasts you.")
                print ("Looks like your luck has finally run out.")
                print ("Ending 28 of 30: GAME OVER")
                run_game()
            elif action == "grab tail":
                print ("You dash towards the side of the turtle and grab it by the tail")
                print ("You proceed to spin around multiple times until you pick up momentum.")
                print ("Finally, you let go of its tail and watch as it flies away into the distance.")
                print ("Was that really necessary?")
                print ("Ending 29 of 30: THE HERO?")
                run_game()


   
